name: hisab_kitab
description: Shared expense tracker with UPI settlements.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.13.2 <4.0.0"

dependencies:
  dynamic_color: ^1.7.0
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  flutter_native_contact_picker: ^0.0.12
  google_mlkit_document_scanner: ^0.6.1
  google_mlkit_text_recognition: ^0.17.1
  image_picker: ^1.2.4
  local_auth: ^3.0.2
  path_provider: ^2.1.6
  pdf: ^3.13.1
  printing: ^5.15.1
  qr_flutter: ^4.1.0
  share_plus: ^13.3.1
  shared_preferences: ^2.5.6
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/fonts/NotoSans-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
